### ISSUE TITLE
Git history is missing

### ISSUE THREAD

**Issue by pulkomandy** [HaikuArchives/jamfile-engine#1]
There is a Git history for this in the repo hosted by Haiku. I don't understand why we set up something on github if it doesn't have the history and it's just to host a single zip file. Do we really not have a simpler way of storing releases for this?

**Comment by jmairboeck** [comment]
The jamfile-engine is already mirrored in the Haiku organization here: https://github.com/haiku/jamfile-engine

**Comment by pulkomandy** [comment]
Yes, I know and I mention it in my message. The releases used to be hosted at haiku-files.org but that was taken down.

Kallisti5 took a backup of the last release and republished it here, but without the git history and without asking me about it (I set up that repo at Haiku side and this is where I plan to continue working on the Jamfile engine). That release is now used for the haikuports recipe.

**Comment by kallisti5** [comment]
Git history corrected here and new tag + hash pushed to haikuports.

jamfile-engine has been stuck in all kinds of weird places over the years. 

Until we have a strategy to automatically generate release artifacts on gerrit / cgit tags, we should avoid using it for things that need packaged.   The https://github.com/haiku/jamfile-engine is a read-only mirror of jamfile engine from our infrastructure.

I support using non-github stuff to reduce our dependence on companies, etc. (it's one reason i'm mirroring Haiku to [codeberg](https://codeberg.org/haiku/haiku)).   However, we need to have a strategy around what this looks like.
